import React, { useState, useEffect } from 'react';
import { Form } from '../types';
import { generateAIInsights } from '../utils/aiAnalysis';
import { Brain, Loader2, FileText } from 'lucide-react';

interface AIInsightsProps {
  form: Form;
}

const AIInsights: React.FC<AIInsightsProps> = ({ form }) => {
  const [insights, setInsights] = useState<string>('');
  const [isLoading, setIsLoading] = useState(false);
  const [hasGenerated, setHasGenerated] = useState(false);

  const generateInsights = async () => {
    setIsLoading(true);
    try {
      const result = await generateAIInsights(form);
      setInsights(result);
      setHasGenerated(true);
    } catch (error) {
      console.error('Error generating insights:', error);
      setInsights('Unable to generate insights at this time. Please try again later.');
    } finally {
      setIsLoading(false);
    }
  };

  const formatInsights = (text: string) => {
    return text.split('\n\n').map((paragraph, index) => {
      // Handle bold text
      const formatted = paragraph.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
      return (
        <p 
          key={index} 
          className="mb-4 text-gray-700 leading-relaxed"
          dangerouslySetInnerHTML={{ __html: formatted }}
        />
      );
    });
  };

  return (
    <div className="max-w-4xl mx-auto">
      <div className="bg-white rounded-lg shadow-md p-6">
        <div className="flex items-center mb-6">
          <div className="p-3 rounded-full bg-purple-100 mr-4">
            <Brain className="h-8 w-8 text-purple-600" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-gray-900">AI-Powered Insights</h2>
            <p className="text-gray-600">
              Get intelligent analysis and recommendations based on your form responses
            </p>
          </div>
        </div>

        {!hasGenerated && !isLoading && (
          <div className="text-center py-8">
            <FileText className="h-16 w-16 text-gray-400 mx-auto mb-4" />
            <p className="text-gray-600 mb-6">
              Generate AI-powered insights from your {form.responses.length} responses
            </p>
            <button
              onClick={generateInsights}
              disabled={form.responses.length === 0}
              className="flex items-center space-x-2 px-6 py-3 bg-purple-600 hover:bg-purple-700 disabled:bg-gray-400 disabled:cursor-not-allowed text-white rounded-md font-medium transition-colors mx-auto"
            >
              <Brain className="h-5 w-5" />
              <span>Generate Insights</span>
            </button>
            {form.responses.length === 0 && (
              <p className="text-sm text-gray-500 mt-2">
                No responses available for analysis
              </p>
            )}
          </div>
        )}

        {isLoading && (
          <div className="text-center py-12">
            <Loader2 className="h-12 w-12 text-purple-600 animate-spin mx-auto mb-4" />
            <p className="text-gray-600">Analyzing responses and generating insights...</p>
            <p className="text-sm text-gray-500 mt-2">This may take a moment</p>
          </div>
        )}

        {hasGenerated && insights && (
          <div className="prose prose-lg max-w-none">
            <div className="bg-gradient-to-r from-purple-50 to-blue-50 rounded-lg p-6 border border-purple-200">
              <h3 className="text-xl font-semibold text-gray-900 mb-4 flex items-center">
                <Brain className="h-6 w-6 text-purple-600 mr-2" />
                Analysis Summary
              </h3>
              <div className="text-gray-700">
                {formatInsights(insights)}
              </div>
            </div>
            
            <div className="mt-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
              <p className="text-sm text-yellow-800">
                <strong>Note:</strong> These insights are generated by AI and should be considered as suggestions. 
                Always validate findings with additional research and domain expertise.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AIInsights;